export const LOGIN = 'LOGIN';

export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'

export const LOGOUT = 'LOGOUT';

export const UPDATE_USERINFO_SUCCEED = 'UPDATE_USERINFO_SUCCEED';

export const UPDATE_USERINFO_FAILED = 'UPDATE_USERINFO_FAILED';

export const SAVE_MY_DEFAULT_CAR = 'SAVE_MY_DEFAULT_CAR';

export const GET_MY_DEFAULT_CAR_SUCCEED = 'GET_MY_DEFAULT_CAR_SUCCEED';

export const GET_MY_DEFAULT_CAR_FAILED = 'GET_MY_DEFAULT_CAR_FAILED';

export const GET_MY_DEFAULT_CAR = 'GET_MY_DEFAULT_CAR';

export const GET_USERINFO = 'GLOBAL_GET_USERINFO'
